apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuer.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: local-ca
    namespace: cert-manager
    files:
      - tls.crt
      - tls.key
