---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  paths-filter:
    runs-on: "ubuntu-latest"
    outputs:
      codechange: "${{ steps.filter.outputs.codechange }}"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "dorny/paths-filter@v2"
        id: "filter"
        with:
          filters: |
            codechange:
              - ".github/workflows/build-test.yaml"
              - "Dockerfile"
              - "go.mod"
              - "go.sum"
              - "cmd/**"
              - "pkg/**"
              - "e2e/**"
              - "internal/**"
  build:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.19"
      - uses: "authzed/actions/go-build@main"

  image-build:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "Build Container Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.19"
      - uses: "authzed/actions/docker-build@main"
        with:
          push: false
          tags: "authzed/spicedb-operator:ci"
          buildx: false
          qemu: false

  test:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.19"
      - uses: "actions/checkout@v3"
        with:
          repository: "authzed/spicedb"
          path: "spicedb"
          submodules: true
      - uses: "docker/setup-qemu-action@v2"
      - uses: "docker/setup-buildx-action@v2"
      - name: "Tag Test SpiceDB Image"
        uses: "docker/build-push-action@v3"
        with:
          context: "spicedb"
          file: "spicedb/Dockerfile"
          tags: "spicedb:dev,spicedb:updated"
          outputs: "type=docker,dest=/tmp/image.tar"
      - name: "Run Ginkgo Tests"
        run: "go run github.com/onsi/ginkgo/v2/ginkgo --skip-package ./spicedb --tags=e2e -r --procs=2 -v --randomize-all --randomize-suites --fail-on-pending --fail-fast --no-color --race --trace --json-report=report.json -- -v=4"
        env:
          PROVISION: "true"
          ARCHIVES: "/tmp/image.tar"
