---
name: "Build & Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
env:
  GO_VERSION: "~1.19"
jobs:
  paths-filter:
    runs-on: "ubuntu-latest"
    outputs:
      codechange: "${{ steps.filter.outputs.codechange }}"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "dorny/paths-filter@v2"
        id: "filter"
        with:
          filters: |
            codechange:
              - ".github/workflows/build-test.yaml"
              - "Dockerfile"
              - "go.mod"
              - "go.sum"
              - "cmd/**"
              - "pkg/**"
              - "e2e/**"
              - "internal/**"
  build:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "Build Binary"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "authzed/actions/go-build@main"

  image-build:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "Build Container Image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "authzed/actions/docker-build@main"
        with:
          push: false
          tags: "authzed/spicedb-operator:ci"
          buildx: false
          qemu: false

  unit:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "Unit Tests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "docker/setup-qemu-action@v2"
      - uses: "docker/setup-buildx-action@v2"
      - name: "Run Unit Tests"
        uses: "magefile/mage-action@v2"
        with:
          version: "latest"
          args: "test:unit"

  e2e:
    needs: "paths-filter"
    if: |
      needs.paths-filter.outputs.codechange == 'true'
    name: "E2E Tests"
    runs-on: "ubuntu-latest-8-cores"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: "authzed/actions/setup-go@main"
        with:
          go-version: "${{ env.GO_VERSION }}"
      - uses: "docker/setup-qemu-action@v2"
      - uses: "docker/setup-buildx-action@v2"
      - name: "Run E2E Tests"
        uses: "magefile/mage-action@v2"
        with:
          version: "latest"
          args: "test:e2e"
      - uses: "actions/upload-artifact@v2"
        if: "always()"
        # this upload step is really flaky, don't fail the job if it fails
        continue-on-error: true
        with:
          name: "cluster-state"
          path: "e2e/cluster-state"
