---
name: "Release"
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
permissions:
  contents: "write"
  packages: "write"
jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.19"
      - uses: "authzed/actions/docker-login@main"
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
      - uses: "goreleaser/goreleaser-action@v2"
        with:
          distribution: "goreleaser"
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"

  kustomizer:
    runs-on: "ubuntu-latest"
    env:
      ARTIFACT: "oci://ghcr.io/${{github.repository_owner}}/${{github.event.repository.name}}-manifests"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Setup kustomizer"
        uses: "stefanprodan/kustomizer/action@main"
      - name: "Set operator image in release manifests"
        uses: "mikefarah/yq@master"
        with:
          cmd: |
            yq eval '.images[0].newTag="${{ github.ref_name }}"' -i ./config/kustomization.yaml
      - name: "Push release manifests"
        run: |
          kustomizer push artifact ${ARTIFACT}:${{ github.ref_name }} -k ./config \
            --source=${{ github.repositoryUrl }} \
            --revision="${{ github.ref_name }}/${{ github.sha }}"
      - name: "Tag latest release manifests"
        run: |
          kustomizer tag artifact ${ARTIFACT}:${GITHUB_REF_NAME} latest
